### ISSUE TITLE
offset parameter to search - does it really work for you?

### ISSUE THREAD

**Issue by JerryNorbury** [pipitone/rdrugshortages#4]
I'm trying to solve an issue with api calls to this same website but then from inside Power query (in Excel).

You seem to have implemented a search_all function by using the query$offset parameter HOWEVER, when I try this using power query my URL is rejected.

Can you confirm your search_all works?

Do you have an example of the GET URL ?

Thanks

Jerry
Amsterdam

**Comment by pipitone** [comment]
Hi Jerry. Yes I just double-checked and offset does work for me!

```sh
$ curl -G https://www.drugshortagescanada.ca/api/v1/search \
   -H 'auth-token: YOURAUTHTOKENHERE' \
   -d 'offset=2001'
```

The result I get: 
```
{
  "total": 18923,
  "limit": 20,
  "offset": 2001,
  "page": 102,
  "remaining": 16883,
  "data": [
    {
    // lots of data
    }
}
```

In other words, the URL you use is `https://www.drugshortagescanada.ca/api/v1/search?offset=` plus whatever other query parameters you want.  Funny you ask though, because when I look over the [API documentation](https://www.drugshortagescanada.ca/blog/52) using `offset` as a `/search` parameter is not mentioned... I guess it's undocumented (or was documented?)

**Comment by JerryNorbury** [comment]
Thanks for the confirmation Jon.
